name: assistant
version: 1.0.0
description: Ассистент рыбака

android:
  package_name: ru.fisher.assistant
  min_sdk_version: 21
  target_sdk_version: 33
  permissions:
    - INTERNET
    - READ_EXTERNAL_STORAGE
